// Model for a forward-looking maintenance schedule generated by Gemini from a
// vehicle's service history plus the owner's driving profile.

/// A single upcoming service — one row of the schedule.
class MaintenanceItem {
  final String task;
  final String dueDate; // approximate due date or timeframe
  final String dueOdometer; // approximate due mileage
  final String priority; // high | medium | low
  final String notes; // short reasoning, may reference the driving profile

  const MaintenanceItem({
    required this.task,
    required this.dueDate,
    required this.dueOdometer,
    required this.priority,
    required this.notes,
  });

  factory MaintenanceItem.fromJson(Map<String, dynamic> json) {
    return MaintenanceItem(
      task: json['task'] as String? ?? '',
      dueDate: json['dueDate'] as String? ?? '',
      dueOdometer: json['dueOdometer'] as String? ?? '',
      priority: (json['priority'] as String? ?? 'medium').toLowerCase(),
      notes: json['notes'] as String? ?? '',
    );
  }
}

/// The full generated schedule: the list of upcoming services.
class MaintenanceSchedule {
  final List<MaintenanceItem> items;

  const MaintenanceSchedule({required this.items});

  factory MaintenanceSchedule.fromJson(Map<String, dynamic> json) {
    return MaintenanceSchedule(
      items: (json['items'] as List<dynamic>? ?? const [])
          .map((e) => MaintenanceItem.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }
}
